#!/bin/bash

. $(dirname $0)/config

if [ -f "${TEMP_DIR}/install_device" ];then
  . ${TEMP_DIR}/install_device
elif [ $# -eq 1 ];then
  disk=$1
else
  echo "$0 path_to_device"
  exit 1
fi

mkfs.vfat ${disk}1
sleep 1

