#!/bin/bash

. $(dirname $0)/config

if [ -f "${TEMP_DIR}/install_device" ];then
  . ${TEMP_DIR}/install_device
elif [ $# -eq 1 ];then
  disk=$1
else
  echo "$0 path_to_device"
  exit 1
fi

#generate temp fstab
rm -f ${TEMP_DIR}/fstab
printf "/dev/zvol/rpool/swap\tnone\t\tswap\t\tdefaults\t0 0\n" >>${TEMP_DIR}/fstab
printf "UUID=%b\t\t/boot/efi\t\tvfat\t\tumask=0077,shortname=winnt\t0 0\n" $(lsblk -o UUID ${disk}1|tail -n1) >>${TEMP_DIR}/fstab
printf "rpool/tmp\t\t/tmp\t\tzfs\tdefaults\t0 0\n" >> ${TEMP_DIR}/fstab

