#!/bin/bash

. $(dirname $0)/config



dnf -y --installroot=${SYSROOT} --releasever=26 install \
  @core kernel \
  @standard \
  zfs zfs-dracut \
  efibootmgr \
  vim-enhanced htop \
  bash-completion \
  grub2-efi grub2-efi-modules \
  acpid


#script=$(mktemp -u )
#
#cat > ${SYSROOT}/$script <<EOF
#dnf -y install \
#  @core kernel \
#  @standard \
#  zfs zfs-dracut \
#  efibootmgr \
#  vim-enhanced htop \
#  grub2-efi grub2-efi-modules \
#  acpid
#EOF
#chmod 755 ${SYSROOT}/$script
#
#chroot ${SYSROOT} $script
#
#rm -f ${SYSROOT}/$script

