#!/bin/bash

. $(dirname $0)/config

script=$(mktemp -u)
cat > ${SYSROOT}/$script <<EOF
dnf -y enable tofik/zfs
dnf -y install \
  @core kernel \
  @standard \
  zfs zfs-dracut zfs-rootfs \
  zfs-beadm zfs-beadm-dracut zfs-beadm-grub2-tools \
  efibootmgr \
  vim-enhanced htop \
  bash-completion \
  grub2-efi grub2-efi-modules shim \
  acpid python3-dnf-plugin-beadm 
EOF
chmod 755 ${SYSROOT}/$script
chroot ${SYSROOT} $script
rm -f ${SYSROOT}/$script

