#!/bin/bash

. $(dirname $0)/config

script=$(mktemp -u)
cat > ${SYSROOT}/$script <<EOF
dnf -y enable tofik/zfs
dnf -y install \
  @core kernel \
  @standard \
  zfs zfs-dracut zfs-rootfs \
  zfs-beadm zfs-beadm-dracut \
  efibootmgr \
  vim-enhanced htop \
  bash-completion \
  grub2-efi grub2-efi-modules shim \
  acpid
EOF
chmod 755 ${SYSROOT}/$script
chroot ${SYSROOT} $script
rm -f ${SYSROOT}/$script

