#!/bin/bash

. $(dirname $0)/config

script=$(mktemp -u)
cat > ${SYSROOT}/$script <<EOF
dnf -y install \
  xorg-x11-drv-libinput \
  xorg-x11-server-Xorg \
  lightdm \
  @Xfce
systemctl enable lightdm
systemctl set-default graphical.target
EOF
chmod 755 ${SYSROOT}/$script
chroot ${SYSROOT} $script
rm -f ${SYSROOT}/$script

