#!/bin/bash

. $(dirname $0)/config



#grap root password
echo "Set root password"
while true;do
  read -s -p "Password: " password
  echo
  read -s -p "Repeat password: " password2
  echo
  if [ "x$password" == "x$password2" ];then
    break
  fi
  echo "Passwords didn't match"
done


echo "Set hostname"
read -p "Hostname: " hostname

echo "Set locale"
read -p "Locale (default en_US.utf8): " locale
if [[ -z "$locale" ]];then
  locale='en_US.utf8'
fi

read -p "Timezone (default: Europe/Warsaw): " timezone
[[ -z "$timezone" ]] && timezone='Europe/Warsaw'

script=$(mktemp -u )

cat > ${SYSROOT}/$script <<EOF
#!/bin/bash
authconfig --enableshadow --passalgo=sha512 --enablesssd --enablesssdauth --update
echo '$password' | passwd --stdin root
echo 'LANG="${locale}"' > /etc/locale.conf
ln -fs ../usr/share/zoneinfo/${timezone} /etc/localtime
echo ${hostname} > /etc/hostname
EOF
chmod 755 ${SYSROOT}/$script

setenforce 0
chroot ${SYSROOT} $script
setenforce 1

rm -f ${SYSROOT}/$script

