#!/bin/bash

. $(dirname $0)/config

script=$(mktemp -u )

cat > ${SYSROOT}/$script <<EOF
#!/bin/bash
systemctl preset zfs-import-cache zfs-import-scan zfs-mount zfs-share zfs-zed zfs.target
systemctl enable zfs-import-scan
EOF
chmod 755 ${SYSROOT}/$script
chroot ${SYSROOT} $script
rm -f ${SYSROOT}/$script

