#!/bin/bash

. $(dirname $0)/config

dropin_dir=${SYSROOT}/etc/systemd/system

#force mounting zfs before reaching local-fs target
mkdir -p ${dropin_dir}/local-fs.target.d
cat >${dropin_dir}/local-fs.target.d/zfs.conf << EOF
#ZFS related dependencies
[Unit]
Wants=zfs-mount.service
EOF

mkdir -p ${dropin_dir}/zfs-mount.service.d
cat >${dropin_dir}/zfs-mount.service.d/dependencies.conf << EOF
#ZFS related dependencies
[Unit]
Before=systemd-rfkill.service systemd-random-seed.service
EOF

mkdir -p ${dropin_dir}/systemd-backlight@.service.d
cat >${dropin_dir}/systemd-backlight@.service.d/zfs.conf << EOF
#ZFS related dependencies
[Unit]
After=zfs-mount.service
EOF

