#!/bin/bash

. $(dirname $0)/config
. ${TEMP_DIR}/install_device

mkdir ${SYSROOT}/keys
chmod 700 ${SYSROOT}/keys
cat > ${SYSROOT}/etc/dracut.conf.d/99-crypto_keys_in_initrd.conf <<EOF
#Allows to type password only once
# dd bs=512 count=8 if=/dev/urandom of=/keys/cryptoroot_keyfile.bin
# cryptosetup luksAddKey ${luks_device} /keys/cryptoroot_keyfile.bin
# add keypath to last column in /etc/crypttab
install_optional_items+="/keys/cryptoroot_keyfile.bin"
EOF

